# Generated by Django 4.2.4 on 2023-08-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papermodels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
